"""empty message

Revision ID: 342dfe2d9f50
Revises: 65668ba72269
Create Date: 2022-01-15 08:56:37.954968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342dfe2d9f50'
down_revision = '65668ba72269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'comments')
    # ### end Alembic commands ###
