"""empty message

Revision ID: 3aaa564692ef
Revises: 8f3b3575a6c8
Create Date: 2021-12-28 17:14:13.027079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aaa564692ef'
down_revision = '8f3b3575a6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('PCU', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'PCU')
    # ### end Alembic commands ###
