"""empty message

Revision ID: dd87aeb1747e
Revises: 3aaa564692ef
Create Date: 2022-01-01 11:05:41.701806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd87aeb1747e'
down_revision = '3aaa564692ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('doctor_code', sa.String(length=20), nullable=True))
    op.drop_column('cases', 'coctor_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('coctor_code', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('cases', 'doctor_code')
    # ### end Alembic commands ###
